# Generated by Django 2.2.3 on 2019-07-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.CharField(max_length=50, verbose_name='图片'),
        ),
    ]
